-- 清空运行时业务与 Flowable 实例/历史（保留 ACT_RE_* 流程定义）
-- 然后请再执行 02_data.sql 重灌用户种子
USE `power`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `wf_urge_log`;
TRUNCATE TABLE `wf_cc`;
TRUNCATE TABLE `wf_leave`;
TRUNCATE TABLE `sys_outbox`;

TRUNCATE TABLE `ACT_RU_VARIABLE`;
TRUNCATE TABLE `ACT_RU_IDENTITYLINK`;
TRUNCATE TABLE `ACT_RU_TASK`;
TRUNCATE TABLE `ACT_RU_EXECUTION`;
TRUNCATE TABLE `ACT_RU_ACTINST`;
TRUNCATE TABLE `ACT_RU_DEADLETTER_JOB`;
TRUNCATE TABLE `ACT_RU_SUSPENDED_JOB`;
TRUNCATE TABLE `ACT_RU_TIMER_JOB`;
TRUNCATE TABLE `ACT_RU_EXTERNAL_JOB`;
TRUNCATE TABLE `ACT_RU_JOB`;
TRUNCATE TABLE `ACT_RU_EVENT_SUBSCR`;
TRUNCATE TABLE `ACT_HI_VARINST`;
TRUNCATE TABLE `ACT_HI_IDENTITYLINK`;
TRUNCATE TABLE `ACT_HI_TASKINST`;
TRUNCATE TABLE `ACT_HI_ACTINST`;
TRUNCATE TABLE `ACT_HI_DETAIL`;
TRUNCATE TABLE `ACT_HI_COMMENT`;
TRUNCATE TABLE `ACT_HI_ATTACHMENT`;
TRUNCATE TABLE `ACT_HI_PROCINST`;

SET FOREIGN_KEY_CHECKS = 1;
